"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 10000

[bun]
symbol = " "

[c]
symbol = " "

[cmake]
symbol = " "

[deno]
detect_files = [
    "deno.json",
    "deno.jsonc",
    "deno.lock",
    "mod.ts",
    "mod.js",
    "deps.ts",
    "deps.js",
    ".dvmrc",
]
symbol = " "

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[elm]
symbol = " "

[git_branch]
style = "bold bright-green"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[lua]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[shell]
disabled = false
elvish_indicator = "~"
format = "[$indicator]($style)"

[terraform]
symbol = " "

[typst]
symbol = " "
